name: Login

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Chckout Repository
        uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Install Cypress
        run: npm install --save-dev cypress@latest

      - name: Run Cypress Tests
        run: npx cypress run
        
